### ISSUE TITLE
Upload example data.csv and data.cfg files

### ISSUE THREAD

**Issue by srmulcahy** [anoda/UPbplot.py#1]
I'm really excited to try this!  Could you please load an example data.csv and data.cfg file?  The ones used in the publication would be great, because if a use could reproduce the figures, they could feel confident using their own data.

**Comment by anoda** [comment]
I uploaded some samples of input (csv and cfg) and output (pdf) files in "examples" directory.

**Comment by srmulcahy** [comment]
That's excellent, thank you!
