### ISSUE TITLE
Upper intercept ages?

### ISSUE THREAD

**Issue by zimshady** [anoda/UPbplot.py#2]
Hi Dr. Noda,

In your latest iteration of the UPb code, I cannot find any function to calculate the upper intercept ages. Am I missing something and if not, are you able to add such functionality?

**Comment by anoda** [comment]
Sorry, the upper interception is not yet functioned in the present script.  I will add it in the future version, if time permits.

**Comment by anoda** [comment]
I just released a new version that includes functions to calculate upper/lower intercept ages.
